# Generated by Django 5.0.4 on 2024-05-15 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainSite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-pub_date",),
            },
        ),
    ]
